Tweak syntax for page name refs
ocaml/odoc pull request #622
Opened 2021-03-05 11:18 UTC by lubegasimon

2021-03-05 11:21 UTC, lubegasimon commented on src/model/reference.ml
> +        if s.[0] = '"' && s.[f_occurence] = '"' then
I’m still failing to handle a case like `{!”Foo”. “Bar”}` whose test is at https://github.com/ocaml/odoc/pull/622/commits/e4a86e69850fb694aa11fffadfae6030ecbd5a7f#diff-f59d447ba8018121335d4cfbebc893d052260724d49e9c187d9f4d7e2f7685ff

2021-03-05 15:01 UTC, jonludlam commented on src/parser/token.ml
> +  | (* | `Quote *)
These should be removed

2021-03-05 15:03 UTC, jonludlam commented
It'd be good to add some test cases to the parser tests - test/parser/test.ml, since when we remove the parser these tests will go with it.

2021-03-07 13:24 UTC, lubegasimon commented on src/model/reference.ml
> +        if s.[0] = '"' && s.[f_occurence] = '"' then
Done!

2021-03-07 13:24 UTC, lubegasimon commented on src/parser/token.ml
> +  | (* | `Quote *)
Done!

2021-03-08 17:51 UTC, Julow requested changes

2021-03-08 17:51 UTC, Julow commented on src/model/reference.ml
> +        if s.[0] = '"' && s.[f_occurence] = '"' then
This is wrong. (eg. `{!"Foo.1.2.3"."Bar.1.2.3"."Baz"}`).
The main mistake is `f_occurence`, which should be `index`. The parser works from right to left, `index` is the right quote and `l_occurence` is the corresponding left quote, nothing more needed.
The current value for `f_occurence` is the first quote of the string, we don't want that.

2021-03-08 17:51 UTC, Julow commented on src/model/reference.ml
> +    | '"' ->
```suggestion
    | '"' when open_parenthesis_count = 0 ->
```

2021-03-08 17:51 UTC, Julow commented on src/model/reference.ml
> +        let identifier = String.trim (String.sub s off_set length) in
`identifier_ended` is also checking that the identifier isn't `""`, `identifier_ended` should be called from here. (so you have the `location`, which will need adjustment to include the quotes)

2021-03-08 17:51 UTC, Julow commented on src/model/reference.ml
> +          scan_kind identifier location (f_occurence - 1) (l_occurence - 1)
The `location` is the wrong one, see the comment about `identifier_ended` above.

We cannot call `scan_kind` without checking the next character first. Here we expect three things:
- `-`, to call `scan_kind`
- `.`, an identifier with no kind, recurse
- beginning of the string, an identifier with no kind, return

2021-03-11 07:59 UTC, lubegasimon commented
> It'd be good to add some test cases to the parser tests - test/parser/test.ml, since when we remove the parser these tests will go with it.

Indeed, I’ll surely address this in an independent PR

2021-03-11 09:20 UTC, jonludlam commented on src/model/reference.ml
> +    | '"' when open_parenthesis_count = 0 -> (
I don't believe we need the `when` clause here.

2021-03-11 16:42 UTC, jonludlam commented
Thanks!

2021-03-11 16:42 UTC, merged